package com.home;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import com.home.domain.Link;
import com.home.repository.LinkRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class LinkTest {
  
  @Autowired
  private LinkRepository linkRepo;
    
  @Test
  void insertLink() {

    String[] data = {"https://qiita.com/rubytomato@github/items/fdfc0a76e848442f374e",
        "WSL (Windows Subsystem for Linux)の基本メモ",
        "http://www.atmarkit.co.jp/ait/articles/1309/27/news116.html",
        "Windowsのrobocopyコマンドでコピーするファイルの種類を選択／変更する",
        "https://qiita.com/arai-wa/items/ceb28523c14177148ce4", "正規表現で大文字や小文字に置換する",
        "https://www.sociomedia.co.jp/category/uidesignpatterns", "UIデザインパターン",
        "http://kh3467.blog66.fc2.com/blog-entry-273.html", "サクラエディタ 指定の文字列以外を削除する",
        "https://www.hellowork.go.jp/member/career_doc01.html", "履歴書・職務経歴書の書き方",
        "http://ksbookshelf.com/nozomu-oohara/Hanrei/index.html", "日本語を読むための漢字辞典",
        "http://blog.daum.net/scan0/2915395", "KANJI 214",
        "https://www.w3schools.com/jquery/jquery_ref_selectors.asp", "jQuery Selectors",
        "https://sys-guard.com/post-14579/", "jQuery Validation 簡単にフォームをチェック バリデーション",
        "https://developer.mozilla.org/ja/docs/Web/JavaScript", "JavaScript",
        "https://qiita.com/arai-wa/items/ceb28523c14177148ce4", "正規表現で大文字や小文字に置換する",
        "http://poppingcarp.com/heroku_postgres/",
        "HerokuにデプロイしたSpring BootアプリからHeroku Postgresを使ってみる",
        "https://qiita.com/arai-wa/items/c2eb7387b5bf37b4ace4", "新人研修でドヤ顔で披露したらウケたEclipseのショートカット集",
        "http://www.devglan.com/spring-boot/spring-boot-angular-example#/restresource",
        "Spring Boot + Angular 5 +Spring Data + Rest Example(CRUD)",
        "https://makuring.com/work/nisa/", "Nisa",
        "https://qiita.com/shoichi0599/items/a419f18c25b36a8a7a0a", "Springメッセージの外部化",
        "https://qiita.com/zephiransas/items/3161d0d1e85a79dadb05", "キャメルケースとスネークケースを相互変換する正規表現",
        "https://dekiru.net/article/5002/#Excel", "ショートカットキー (一覧)",
        "http://www.atmarkit.co.jp/ait/articles/1608/08/news039.html",
        "Windows 10でLinuxプログラムを利用可能にする", "https://qiita.com/tutttuwi/items/a570940c2b42069c5ddd",
        "Apache Sparkのインストールについて", "https://qiita.com/rockhopper/items/0680a537838233fce323",
        "Ubuntu への Apache Spark のインストール", "https://qiita.com/ishida330/items/5302e1493e1d94e86adf",
        "Sparkプログラミングのお勉強～WindowsだけでサクッとIDE環境を作ってみた",
        "https://x1.inkenkun.com/archives/1167#compare", "Apache Spark: SparkSQLリファレンス?演算子編?",
        "http://gihyo.jp/dev/serial/01/test_up/0004", "「状態遷移図」と「状態遷移表」で見えるもの",
        "https://angular.io/guide/styleguide", "angular styleguide(ENG)", "https://angular.jp/docs",
        "angular styleguide(JPN)",
        "https://github.com/shoheyheyhey/angular_shopping_app/tree/master/src/app",
        "Angular CODE very good", "https://mya-ake.com/slides/regret-angular-web-app#18",
        "Angular参考資料", "http://postgresguide.com/utilities/psql.html", "Postgres Guide(ENG)",
        "https://devnote.jp/jstl/", "各種ツール設置方法",
        "https://qiita.com/KevinFQ/items/a6d92ec7b32911e50ffe", "@GeneratedValueを使って主キーを生成する方法",
        "https://qiita.com/gekkoukisi/items/1a621522f34e902511c2",
        "postgres で INSERT時に 「id(主キー) がユニークじゃないよ」と怒られる。",
        "https://realhanbit.co.kr/books/235/pages/0/read", "JPA参考サイト（KRN）",
        "https://material.angular.io/guides", "material.angular.io(ENG)",
        "https://medium.com/codingthesmartway-com-blog/angular-material-and-angular-6-material-design-for-angular-6b1a3ee476f0",
        "Angular Material And Angular 6 — Material Design For Angular",
        "https://github.com/cheese10yun/spring-jpa-best-practices",
        "cheese10yun/spring-jpa-best-practices",
        "https://qiita.com/yyoshikaw/items/32a96332cc12854ca7a3", "Lombok",
        "http://rockdrumy.tistory.com/214", "[JAVA] static키워드 바로알기",
        "https://www.baeldung.com/java-stream-operations-on-strings",
        "Operations with Java Streams", "https://www.baeldung.com/java-8-streams",
        "The Java 8 Stream API Tutorial", "https://qiita.com/takumi-n/items/369dd3fcb9ccb8fcfa44",
        "Java Stream APIをいまさら入門", "https://programmers.co.kr/learn/courses/5/lessons/242",
        "2중 클래스 스태틱", "http://etc9.hatenablog.com/entry/2018/05/17/000257", "Spring boot 参考",
        "https://confrage.jp/eclipse%E3%81%A7%E5%A4%A7%E6%96%87%E5%AD%97%E5%B0%8F%E6%96%87%E5%AD%97%E3%82%92%E5%A4%89%E6%8F%9B%E3%81%99%E3%82%8B%E3%82%B7%E3%83%A7%E3%83%BC%E3%83%88%E3%82%AB%E3%83%83%E3%83%88%E3%82%AD%E3%83%BC/",
        "Eclipseで大文字小文字を変換するショートカットキー",
        "https://www.thoughts-on-java.org/jpa-21-how-to-implement-type-converter/",
        "How to implement a JPA Attribute Converter",
        "http://itdoc.hitachi.co.jp/manuals/link/cosmi_v0870/APR4/EU260076.HTM#ID00310",
        "@JoinColumn", "https://qiita.com/KeithYokoma/items/9681b130ea132cfad64d", "Enum で振る舞う",
        "https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/",
        "Spring Boot Reference Guide(ENG)",
        "https://www.callicoder.com/spring-boot-file-upload-download-rest-api-example/",
        "Spring Boot File Upload / Download Rest API Example",
        "https://qiita.com/tasuku/items/885f490e708187482d93", "GoogleDriveにJavaプログラムでファイルアップロードする",
        "http://ytyaru.hatenablog.com/entry/2017/02/06/000000", "Google APIのRefreshTokenを取得する",
        "http://poppingcarp.com/google_drive_api_call/",
        "【Google API入門（2）】AngularからGoogle Drive APIをコールしてみる",
        "https://github.com/angular/material2/blob/master/CHANGELOG.md",
        "Find file  Copy path  material2/CHANGELOG.md ", "http://javacan.tistory.com/",
        "JavaCan(KRN)",
        "https://www.callicoder.com/spring-boot-jpa-hibernate-postgresql-restful-crud-api-example/",
        "Spring Boot, PostgreSQL, JPA, Hibernate RESTful CRUD API Example",
        "https://qiita.com/kws9/items/3fb72882ac68d5cab2d1", "Webアプリ DB更新時の排他制御",
        "https://medium.com/codingthesmartway-com-blog/angular-material-and-angular-6-material-design-for-angular-6b1a3ee476f0",
        "Angular Material And Angular 6 — Material Design For Angular",
        "http://angular-block-ui.nullest.com/#!/", "Angular BlockUI",
        "https://material.io/tools/icons/?style=baseline", "Angular Material icons ",
        "http://itdoc.hitachi.co.jp/manuals/3000/3000349340/A4930067.HTM",
        "Hitachi Multi Payment Network communications server 概説",
        "https://qiita.com/ne-peer/items/c1074bdbf752b831f749",
        "Angular Materialでマテリアルでレスポンシブなリストを実装する",
        "https://qiita.com/chibi929/items/3577a8b0a2d751dc6bb6",
        "Angular Material の \"Datepicker\" の見た目と戦う", "https://engineers.weddingpark.co.jp/?p=662",
        "【DB設計入門|ER図|MySQL】コンビニレシートから学ぶ！データモデリング手法",
        "https://support.office.com/ja-jp/article/%E5%B0%8F%E5%86%8A%E5%AD%90%E3%81%BE%E3%81%9F%E3%81%AF%E6%9C%AC%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B-dfd94694-fa4f-4c71-a1c7-737c31539e4a",
        "小冊子または本を作成する", "http://www.oss.mlit.go.jp/portal/beginner/yougoshuu/index.html",
        "自動車保有関係手続のワンストップサービス（以下、当サービス）で使用している用語",
        "https://www.relief.jp/docs/excel-vba-wright-texts-in-textboxes-to-cells.html",
        "https://www.relief.jp/docs/excel-vba-wright-texts-in-textboxes-to-cells.html",
        "https://mosapride.com/index.php/2018/06/18/post-1038/#i", "【Angular】電子書籍っぽいサイトの技術的なとこ",
        "https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html",
        "Part IV. Spring Boot features",
        "https://qiita.com/rubytomato@github/items/0baf1df5b3eb7094cc41",
        "[JUnit]Spring Bootとユニットテスト環境の設計について",
        "https://qiita.com/dais39/items/63c8364d96990d5af0a4",
        "[JUnit]＠SpringApplicationConfiguration -> ＠SpringBootTestに書き換えたときにハマったところ",
        "https://blog.pepese.com/entry/2017/01/21/182343",
        "[JUnit]ぺーぺーSEのブログ（Spring BootでJUnitテスト ）",
        "http://reosablo.hatenablog.jp/entry/2015/02/25/001130", "【util】Windows標準環境でファイル分割 ",
        "https://excelkamiwaza.com/sheets_save.html", "【EXCEL】EXCEL シート毎にファイル分割保存する方法／マクロ(VBA)で解決！",
        "https://www.jaspa.or.jp/portals/pdf/OSS_usermanual_intro_201809.pdf", "【参考資料】",
        "https://blog.angular-university.io/angular-material-dialog/",
        "Angular Material Dialog: A Complete Example",
        "http://www.atmarkit.co.jp/ait/spv/1805/18/news022.html",
        "BFF（Backends For Frontends）の5つの便利なユースケース", "https://cloudear.jp/blog/?p=2101",
        "【JPA】JPAを深掘りする〜Criteria APIで型安全な検索を追求しよう！【基本編】",
        "https://qiita.com/shindooo/items/815d651a72f568112910",
        "【JAVA】Java 8 \"Optional\" ～ これからのnullとの付き合い方 ～",
        "https://speakerdeck.com/masatoshitada/spring-data-jpa-in-50min?slide=17",
        "【SpringBoot】Spring Data JPA環境設定", "https://qiita.com/tbpgr/items/989c6badefff69377da7",
        "【MarkDown】Markdown記法 サンプル集",
        "https://www.ibm.com/developerworks/jp/java/library/j-java8idioms6/index.html",
        "【Java】ラムダ式を作成する 2 つの方法", "https://qiita.com/SUZUKI_Masaya/items/6476dbbcb3e369640c78",
        "【MarkDown】ブラウザでMarkdownを表示する方法",
        "https://stackoverflow.com/questions/35442329/visualizing-readme-md-files-in-my-website",
        "【MarkDown】ライブラリ使用例", "https://qiita.com/natsumo/items/717e40de2c43824624b6",
        "【GitHub】マークダウンで簡単にスライド資料を作成する方法",
        "http://www.jada.or.jp/contents/img/af3fc87c112aa323924ff7bf01609166.pdf",
        "OSS 申請共同利用システム操作マニュアル", "https://www.abbreviations.com/PRINT", "Acronyms & Abbreviations",
        "https://www.aina.or.jp/wp-content/themes/ainas_pc/pdf/proxy/proxy_t_tantosha-kanri.pdf",
        "OSS 申請共同利用システム操作マニュアル【代理人編 管理】",
        "https://www.jaspa.or.jp/portals/pdf/OSS_usermanual_intro_201804.pdf",
        "継続検査ＯＳＳ代理申請ご利用マニュアル（導入編）",
        "https://www.aina.or.jp/wp-content/themes/ainas_pc/pdf/proxy/proxy_t_ainas_outline.pdf",
        "OSS 申請共同利用システム【AINAS 概要編】",
        "https://www.jaspa.or.jp/portals/pdf/OSS_JASPA_applicationform_201712.pdf",
        "日整連 代理申請利用申込書 ",
        "https://www.jaspa.or.jp/portals/pdf/AINAS_application-request_201712.pdf",
        "OSS申請共同利用システム（AINAS）利用申請書", "https://www.jaspa.or.jp/portals/pdf/u_manual5_ver1.3.0.pdf",
        "保適証サービス（電子保安基準適合証システム）ご利用マニュアル", "https://allabout.co.jp/gm/gc/23897/3/",
        "スタイルシートの class と id の違いと使い分け", "https://github.com/madvirus/ddd-start", "DDD Start",
        "https://qiita.com/sunstripe/items/9230396febfab2eae2c2", "json1",
        "https://qiita.com/panichi/items/7e17820d02fa274bf04a", "Angularチュートリアル + Spring Bootやってみた",
        "https://sendgrid.kke.co.jp/blog/?p=8673", "Postmanを使ってWeb APIにアクセスする その1",
        "https://service.plan-b.co.jp/blog/tech/10503/", "【情報】SPAを開発する際の重要ポイント",
        "https://qiita.com/KevinFQ/items/a6d92ec7b32911e50ffe",
        "【JPA】@GeneratedValueを使って主キーを生成する方法",
        "https://www.gwtcenter.com/event-handling-and-lamda-expr", "Javaのイベント処理とラムダ式",
        "https://qiita.com/euledge/items/a224777c15ae7145114a", "【Powermock】",
        "http://montai-garage.sakura.ne.jp/junit03/", "【PowerMock】maven",
        "https://jojoldu.tistory.com/320", "【JUNIT】@SpyBean @MockBean 의도적으로 사용하지 않기",
        "https://qiita.com/gengogo5/items/933ca7b959215f464e51",
        "[JUNIT]JUnitでprivateメソッドのテストをする場合に注意すること", "https://www.qoosky.io/techs/84b9daad5c",
        "JUnIT.Spring Boot の単体テストと結合テストの例", "https://qiita.com/rs_/items/ad1dbdbd439728a1ed97",
        "【JUnit】JUnit備忘録", "https://qiita.com/java-beginner/items/9fc60e3754445a57266e",
        "(Java)変数の初期値（Java言語仕様4.12.5）", "https://www.qoosky.io/techs/84b9daad5c",
        "Spring Boot の単体テストと結合テストの例",
        "https://qiita.com/rubytomato@github/items/0baf1df5b3eb7094cc41",
        "Spring Bootとユニットテスト環境の設計について",
        "http://huruyosi.hatenablog.com/entry/springboot%E3%81%A7context_path",
        "spring boot で context-pathを設定する", "https://qiita.com/oohira/items/f1045d734a80e385f545",
        "PDF 比較", "https://dotinstall.com/lessons/basic_emmet_v3/50301", "Emment使い方紹介",
        "https://www.baeldung.com/rest-search-language-spring-jpa-criteria",
        "(JPA)REST Query Language with Spring and JPA Criteria",
        "https://www.slideshare.net/mobile/yuukifukuda378/ss-46878413", "ramda",
        "https://hojak99.tistory.com/m/503", "[Spring] Spring JPA Specification",
        "https://qiita.com/mitsuya/items/be50dc329b4f3abe5ac5",
        "【Test】Spring Bootでテストを書くときのやりかたまとめ",
        "http://javatechnology.net/other/maven-copy-dependencies/",
        "【Maven】依存ライブラリを特定のディレクトリに取得する方法", "https://lifezipang.com/visa-info/work-visa-renewal/",
        "【ビザ申請】", "https://biz.trans-suite.jp/2141", "【いずれも、いづれか】",
        "https://qiita.com/opengl-8080/items/eaa8f4eb9286a3df7986", "Spring Security 使い方メモ　テスト",
        "https://codezine.jp/article/corner/653",
        "Angular」の活用 SEO対策やページ表示速度アップに有効！「Angular」のサーバーサイドレンダリング",
        "https://www.npmjs.com/package/ngx-markdown", "【ngx-markdown】",
        "https://note.mu/strictlyes/n/n563b3803b41c", "レコメンドシステム入門。",
        "https://dev.classmethod.jp/architecture/persisten-login-for-webapp/", "ログイン処理",
        "https://qiita.com/kensuket1216/items/bd0f3636724f652aa3fa",
        "【Formatter】Eclipseでコーディング規約を自動で修正して保存する", "https://webkikaku.co.jp/blog/htmlcss/preload/",
        "サイト高速化に必須の link rel=preload とは？（使い方とサンプルHTML・CSS）", "https://biz.trans-suite.jp/15596",
        "「以降」に当日は入る？意味や類語なども詳しく解説", "https://www.sejuku.net/blog/20714", "DateクラスのcompareToメソッド",
        "https://qiita.com/t-sagiri/items/387c2bcb6e3871cf951e", "Github API v3を初めて使ってみた【Token】",
        "https://qiita.com/taro_dev/items/f6a30ffa617fde9abb23", "Apache POIを使ってExcel出力する！",
        "http://pineplanter.moo.jp/non-it-salaryman/2018/05/14/javafx-filechooser/",
        "JavaFXでファイルダイアログ（FileChooser）", "https://www.baeldung.com/spring-data-ddd",
        "DDD Aggregates and @DomainEvents",
        "https://confrage.jp/java8%E3%81%AEstringjoiner%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9/",
        "Java8のStringJoinerの使い方", "https://saruwakakun.com/html-css/basic/div-span",
        "divとspanの違いは？使い分け方を初心者向けに解説", "https://www.marineroad.com/staff-blog/17761.html",
        "[Java] Spring BootでThymeleafを使ってみよう！（応用編）",
        "https://qiita.com/nola1176/items/d937b7cf2cd5324cb992",
        "Spring Boot + Thymeleaf BootStrap導入方法メモ", "https://codezine.jp/article/detail/11516?p=2",
        "Angular Material」で、「Angular」のWebページにMaterial Designを導入しよう",
        "https://github.com/zerockcode", "Spring Boot 2",
        "https://laboradian.com/installation-and-setting-of-wsl/",
        "WSL (Windows Subsystem for Linux) の導入と設定",
        "https://qiita.com/take_3/items/8f95d9c185a7a7d5bf77", "【BATCH】テストで巨大で固定長なファイルを扱うtips",
        "https://hulftorangelab.zendesk.com/hc/ja/articles/226888147-%E5%AE%9F%E8%B7%B5-%E3%83%87%E3%83%BC%E3%82%BF%E5%A4%89%E6%8F%9B-%E5%9B%BA%E5%AE%9A%E9%95%B7-CSV-%E3%83%87%E3%83%BC%E3%82%BF%E5%A4%89%E6%8F%9B%E7%B7%A8-",
        "DataMagic使い方", "https://docs.emmet.io/cheat-sheet/", "【Emmet】Documentation cheat-sheet",
        "https://qiita.com/c-cho/items/a5ba13aaebb91bab98ab",
        "【JAVA】try-catch-finally、try-with-resources、そして発生した例外たち",
        "https://codezine.jp/article/detail/11673", "Spring Bootでバックエンドシステムを作成しよう",
        "https://codezine.jp/article/detail/11642?p=3", "「簡単な話から始めよう！」～ソフトウェア開発者に贈るテクニカルライティングの極意",
        "https://qiita.com/riekure/items/7348a600e18b7d6d0f72",
        "(Java7以降限定)オブジェクトはObjects.equalsで比較してほしい",
        "https://employment.en-japan.com/engineerhub/entry/2019/10/03/103000",
        "「単体テスト」再入門！ 開発の現場でバグを確実に洗い出す最適な手法と、テストケースの作り方",
        "https://coliss.com/articles/build-websites/operation/css/a-modern-css-reset.html",
        "古いCSSリセットからはもう卒業！モダンブラウザに適した新しいCSSリセット -A Modern CSS Reset",
        "https://www.ipa.go.jp/sec/softwareengineering/reports/20100331.html", "【独立行政法人 情報処理推進機構】",
        "https://pm-rasinban.com/bd-write", "【若手プロマネの羅針盤】",
        "https://webdesignfacts.net/entry/animation-tabbar/",
        "スマホサイト用アニメーション付きフッターfixed固定メニューHTML&CSS12選！簡単コピペで使用可！【タブバー/jQuery/デモ】",
        "https://coliss.com/articles/build-websites/operation/css/popular-layouts-and-patterns-made-with-css.html",
        "よく使われるレイアウトやUIコンポーネント、それだけを実装するためのHTMLとCSSのシンプルなコードのまとめ",
        "https://qiita.com/wrongwrong/items/d3060a9094f59cfead31",
        "【SpringBoot】アップロードするMultipartFileの最大サイズを変更する",
        "https://qiita.com/5zm/items/0864d6641c65f976d415",
        "絶対分かるMyBatis！MyBatisで覚えるべきチェックルール25（中編）",
        "https://qiita.com/5zm/items/e1faac61a1d00998fb1f",
        "絶対分かるMyBatis！MyBatisで覚えるべきチェックルール25（前半）",
        "https://qiita.com/rs_/items/420109480bc8ab72d55b", "MyBatis備忘録",
        "https://qiita.com/mun_takamatsu/items/1a64134cf6d4f5218e6e",
        "（ハンズオン用）HTMLをJavaScriptで効率よく組み立てる方法",
        "https://www.logicbig.com/how-to/visual-studio-code/remove-vs-code-completely.html",
        "How to completely uninstall/remove Visual Studio Code IDE?",
        "https://qiita.com/koukibuu3/items/77734596483ffd788931", "SpringBootをVSCodeで使ってみる",
        "https://qiita.com/nulltemp/items/12d9c071da9e450e5eb8", "Spring Frameworkの多国語対応",
        "https://o7planning.org/en/11889/manipulating-files-and-folders-on-google-drive-using-java",
        "Manipulating files and folders on Google Drive using Java",
        "https://www.marineroad.com/staff-blog/17761.html",
        "[Java] Spring BootでThymeleafを使ってみよう！（応用編）", "http://photoshopvip.net/119921",
        "コード共有サイトCodepenで2019年に話題となったHTMLスニペット・ベスト100",
        "https://qiita.com/opengl-8080/items/eb3bf3b5301bae398cc2", "Spring Boot で Thymeleaf 使い方メモ",
        "https://leeyuchang.github.io/home/Google%20Drive%20API",
        "https://developers.google.com/drive/api/v3/reference/about/get",
        "https://developers.google.com/drive/api/v3/reference/files/create",
        "Google API File CREATE", "https://qiita.com/riversun/items/76f2305d554228cab4e2",
        "Javaでdata URI (base64) を作る方法", "https://tutorialmore.com/questions-1834588.htm",
        "http post - マルチパートフォームデータと画像をAndroidのサーバーにアップロードする方法は？",
        "https://qiita.com/kossacks/items/8d279bcc1acc2c2153ab",
        "Google API OAuth2.0のアクセストークン&リフレッシュトークン取得手順メモ",
        "https://qiita.com/hanzawak/items/7355142f884cb56a4d57",
        "[GCP]継続的にAPIを利用するための、リフレッシュトークンを用いたアクセストークンの取得方法",
        "https://qiita.com/alpha_pz/items/0a0cd902af1d3904616f", "MybatisのTypeHandlerでEnumを扱う",
        "https://scrapbox.io/tamago324-05149866/Spring_@SessionAttributes_%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AD%E3%83%BC%E3%83%A9%E5%86%85%E3%81%A7%E3%81%AE%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E7%AE%A1%E7%90%86",
        "Spring @SessionAttributes を使ったコントローラ内でのセッション管理",
        "https://qiita.com/rot-z/items/299ac40361690c51ce1d", "Google Drive上のファイルに直接アクセスする",
        "https://www.baeldung.com/spring-bean-scopes", "Quick Guide to Spring Bean Scopes",
        "https://engineers.weddingpark.co.jp/?p=1087", "JavaScriptの非同期処理Promise・async awaitを学んでみた",
        "https://qiita.com/comefigo/items/72a254bad14edf6f621a",
        "Google Drive Apiでファイル取得する(Javascriptで)",
        "https://blog.itkonekt.com/2018/06/27/server-sent-events-in-spring/",
        "Server-Sent Events in Spring",
        "https://golb.hplar.ch/2017/03/Server-Sent-Events-with-Spring.html",
        "Server-Sent Events with Spring", "https://www.baeldung.com/spring-boot-favicon",
        "Guide to the Favicon in Spring Boot",
        "https://qiita.com/NagaokaKenichi/items/380c1316383b2020a1e7",
        "Spring Boot + Mybatisのmapper-locations",
        "https://blog.codefx.org/java/http-2-api-tutorial/", "Java 11 HTTP/2 API Tutorial",
        "https://qiita.com/zaru/items/8c0ab5c70775644d4d41", "最速・最高のファイルアップロードに近づくための1歩",
        "https://dzone.com/articles/java-11-standardized-http-client-api",
        "Java 11: Standardized HTTP Client API",
        "https://developers.google.com/drive/api/v3/performance",
        "Drive_API_v3_Improve performance",
        "https://kazuhira-r.hatenablog.com/entry/20170401/1491058300",
        "Javaの圧縮・解凍ライブラリ（JDK標準GZIP、Commons Compress、snappy-java、LZ4 Java）を試す",
        "https://leeyuchang.github.io/home/[JS]%20%EB%B0%98%EB%B3%B5%EB%AC%B8%20Promise%20/%20async%20&%20await%20%ED%99%9C%EC%9A%A9",
        "https://velog.io/@760kry/JS-%EB%B0%98%EB%B3%B5%EB%AC%B8-Promise-xzk5w6nudx",
        "https://github.com/kamranahmedse/developer-roadmap/tree/master/translations",
        "web-front-end-developer-roadmap",
        "https://velog.io/@thms200/2020-01-28-2301-%EC%9E%91%EC%84%B1%EB%90%A8-fwk5xyifw7",
        "for with Promise",
        "https://www.moongift.jp/2020/04/trollo-vuevuex%e8%a3%bd%e3%81%ae%e3%82%ab%e3%83%b3%e3%83%90%e3%83%b3%e3%82%b7%e3%82%b9%e3%83%86%e3%83%a0/",
        "Trollo - Vue/Vuex製のカンバンシステム",
        "http://blog.snowcait.info/2019/03/23/vue-js-on-github-pages/",
        "vue-cli で作ったサイトを GitHub Pages にデプロイする",
        "https://askubuntu.com/questions/1127055/install-mongodb-shell-client-without-server",
        "install mongodb shell client without server",
        "https://qiita.com/att55/items/2154a8aad8bf1409db2b", "なんとなく CORS がわかる...はもう終わりにする。",
        "https://nelog.jp/amazon-kindle-highlight", "Kindle本のハイライト箇所一覧をEvernoteに読書メモとして保存する方法",
        "https://qiita.com/Nossa/items/e6f503cbb95c8e6967f8#%E5%80%8B%E3%80%85%E3%81%AE%E5%80%A4%E3%81%AB%E5%B1%95%E9%96%8B%E3%81%99%E3%82%8B",
        "【JavaScript】スプレッド構文の便利な使い方まとめ",
        "https://www.telerik.com/blogs/design-patterns-in-javascript",
        "Design Patterns in JavaScript",
        "https://thenextweb.com/syndication/2020/05/14/a-comprehensive-guide-to-javascript-design-patterns/",
        "A comprehensive guide to JavaScript design patterns",
        "https://d2.naver.com/helloworld/10963", "스레드 덤프 분석하기",
        "https://coliss.com/articles/build-websites/operation/css/layouts-and-patterns-made-with-css.html",
        "よく使用されるWebページのレイアウトやUI要素91種類をシンプルなCSSで実装するコードのまとめ -CSS Layout",
        "https://blog.bitsrc.io/10-super-useful-tricks-for-javascript-developers-f1b76691199b",
        "10 Super Useful Tricks for JavaScript Developers",
        "https://medium.com/altcampus/implementing-simple-spa-routing-using-vanilla-javascript-53abe399bf3c",
        "Implementing Simple SPA Routing Using Vanilla JavaScript",
        "https://medium.com/sjk5766/jwt-json-web-token-%EC%86%8C%EA%B0%9C-49e211c65b45",
        "JWT(Json Web Token) 소개",
        "https://blog.logrocket.com/7-ways-to-improve-node-js-performance-at-scale/",
        "7 ways to improve Node.js performance at scale",
        "https://dzone.com/articles/mongodb-design-tips-amp-tricks",
        "MongoDB Design: Tips AND Tricks",
        "https://coliss.com/articles/build-websites/operation/css/css-new-pseudo-classes-is-and-where.html",
        "CSSの新しい疑似クラス:is()と:where() なんだこれ便利すぎる！",
        "https://blog.logrocket.com/javascript-cache-api/", "Working with the JavaScript Cache API",
        "https://english-club.jp/blog/english-phonetic-symbol/", "英語の発音記号｜日本人が苦手な母音と子音を14のコツで矯正！",
        "https://tech.techtouch.jp/entry/vuex-ddd-architecture", "Vuex + DDD のアーキテクチャを考える",
        "https://dev.classmethod.jp/articles/developersio_korea_online_elb/",
        "[발표자료]Elastic Load Balancing로 트래픽 분산해보기",
        "https://dev.classmethod.jp/articles/bad-pattern-of-aws-design/",
        "「はじめてのAWS設計でやりがちな失敗パターンまとめ」について発表しました",
        "https://dzone.com/articles/java-8-parallel-processing-with-completable-future",
        "Java 8 Parallel Processing With Completable Future",
        "https://dev.to/mohammadfarmaan/simple-calculator-with-dark-mode-545c",
        "Simple Calculator with Dark Mode.",
        "https://medium.com/better-programming/node-js-vs-spring-boot-which-should-you-choose-2366c2f76587",
        "Node.js vs. Spring Boot — Which Should You Choose?",
        "https://levelup.gitconnected.com/keep-calm-and-start-coding-how-to-fight-coding-anxiety-dee06efd8b9c",
        "Keep Calm and Start Coding: How to Fight Coding Anxiety",
        "https://dev.to/educative/build-modern-offline-apps-with-progressive-web-apps-4ep8",
        "Build modern, offline apps with Progressive Web Apps",
        "https://dev.to/bhagatparwinder/top-10-vs-code-settings-1bkm", "Top 10 VS Code Settings",
        "https://dev.classmethod.jp/articles/new-graduate-2020-tiger-way-to-get-aws-saa-02/",
        "新卒社員が入社3ヶ月でAWS 認定ソリューションアーキテクト(SAA-02)を取得した話",
        "https://dev.to/blacksonic/you-might-not-need-vuex-with-vue-3-52e4",
        "You Might Not Need Vuex with Vue 3", "https://caingwiz.tistory.com/m/29",
        "아마존(Solution Architect)", "https://qmffjem09.tistory.com/entry/queryDsl-error",
        "QueryDSL Gradle V5.0 error", "https://blog.naver.com/shzpqkfl/221569351354",
        "<JPA> QueryDSL 사용하기 [출처] <JPA> QueryDSL 사용하기|작성자 JohnSuhr",
        "https://m.blog.naver.com/PostList.nhn?blogId=rorean", "[JPA] JPA 시작하기(5) - 복합키",
        "https://bezkoder.com/spring-boot-jwt-auth-mongodb/",
        "Spring Boot, MongoDB: JWT Authentication with Spring Security",
        "https://medium.com/@igniter.yoo/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%ED%8A%B8%EB%A0%88%EC%9D%B4%EB%94%A9%EC%9D%98-%EA%B8%B0%EC%B4%88-%EA%B0%9C%EB%85%90%EA%B3%BC-%EC%98%88%EC%8B%9C-25913a19f95f",
        "알고리즘 트레이딩의 기초: 개념과 예시", "https://reflectoring.io/spring-boot-paging/",
        "Paging with Spring Boot",
        "https://medium.com/@gerard.sans/build-your-first-full-stack-serverless-app-with-vue-and-aws-amplify-9ed7ef9e9926",
        "Build your first full-stack serverless app with Vue and AWS Amplify",
        "https://m.blog.naver.com/weekamp/222084700489",
        "[SpringBoot] SpringBoot로 SpringSecurity 기반의 JWT 토큰 구현하기",
        "https://qiita.com/suin/items/f7ac4de914e9f3f35884", "WebAPIでエラーをどう表現すべき？15のサービスを調査してみた",
        "https://catchdream.tistory.com/129", "Thymeleaf 에서 자바스크립트로 객체 값 전송",
        "https://eblo.tistory.com/48", "RESTful 서비스 설계와 개발 - 메시지와 예외 처리",
        "https://pjh3749.tistory.com/273", "REST API 에러 핸들링 best practice - 에러를 어떻게 내려 주어야 할까",
        "https://tenshoku.mynavi.jp/knowhow/mensetsu", "面接ガイド",
        "https://www.slideshare.net/masatoshitada7/spring-security-meetup",
        "これで怖くない！？コードリーディングで学ぶSpring Security #中央線Meetup", "https://heowc.tistory.com/38",
        "Spring Boot - jar로 Deploy(배포)하기  출처: https://heowc.tistory.com/38 [허원철의 개발 블로그]",
        "https://lts0606.tistory.com/225", "우분투 jar 파일 서비스 등록(Ubuntu service jar file)",
        "https://pages.github.com/", "Websites for you and your projects.",
        "https://medium.com/@pakss328/currenttarget-vs-target-b9dcdb8911ea",
        "currentTarget vs target", "https://www.baeldung.com/spring-security-cors-preflight",
        "Fixing 401s with CORS Preflights and Spring Security",
        "https://codezine.jp/article/detail/12988",
        "2020年9月に売れた「コンピュータ・IT」関係の本、Amazonランキング1位から100位まで", "https://t3guild.com/archives/86",
        "Java의 새로운 날짜 및 시간 관리 방법과 JSON 통신 방법"};

    
    List<Link> lists = new ArrayList<>();

    String key = null;
    for (int i = 0; i < data.length; i++) {
      if (i % 2 == 0) {
        lists.add(new Link(null, key, data[i], LocalDateTime.now().plusSeconds(i)));
      } else {
        key = data[i];
      }
    }

    // linkRepo.saveAll(lists);
  }


  

}

